# Site settings
title: Nancy Truong
email: nancy@nancytruong.com
description: "English and Spanish Translator"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3672FE
  secondary: 2B5BCC  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Nancy Truong
  pic: 1

# Build settings
markdown: kramdown
permalink: pretty